### ISSUE TITLE
Add a link to the student resource packet

### ISSUE THREAD

**Issue by andy-wojciechowski** [msoe-sg/msoe-sg-website#23]
This will need to be hosted somewhere like one drive or Google

**Comment by andy-wojciechowski** [comment]
@techguy4u I'm assigning this to you since you need to get us the student resource packet. I'll un-assign you and assign someone else once this enters development.

**Comment by techguy4u** [comment]
Here is the link to the folder that could be used to host website documents. It currently has the student resource packet as well as a blank about page document.

The link is view only within the organisation, we can discuss changing permissions, but I dont want to share a different link openly.

https://msoe365.sharepoint.com/:f:/s/MSOEStudentGovernment/EgI5I6WlO21DpXcs7UWCH-cBoYF4rfzyImUrsFX84nNJlw?e=a0AVza

**Comment by andy-wojciechowski** [comment]
Closing this as this was released on 4/21/20

**Comment by andy-wojciechowski** [comment]
Reopening this. The build failed when releasing this

**Comment by andy-wojciechowski** [comment]
Fixed the build and confirmed that this was released
