### ISSUE TITLE
Add student government promotional photo to About page

### ISSUE THREAD

**Issue by andy-wojciechowski** [msoe-sg/msoe-sg-website#44]

**Comment by andy-wojciechowski** [comment]
@meghankarbarz I have this written down as one of @techguy4u's ideas. So, I'm assigning this to you to get information about if we want to do this.

**Comment by andy-wojciechowski** [comment]
From discussion on 9/9 we talked about maybe having a photo collage at the top of the about page?

**Comment by meghankarbarz** [comment]
![image](https://user-images.githubusercontent.com/64505167/101399688-6c1c2b00-3895-11eb-8ac7-3a19d3834e3f.png)

**Comment by andy-wojciechowski** [comment]
This has been released
